import { Injectable } from '@nestjs/common';
import sharp = require('sharp');
import * as opentype from 'opentype.js';
import * as path from 'path';
import * as fs from 'fs';

@Injectable()
export class CoverImageService {
  private font: opentype.Font;
  private faviconSvg: string;

  constructor() {
    const assetsDir = path.join(__dirname, '..', 'assets');
    this.font = opentype.loadSync(
      path.join(assetsDir, 'fonts', 'Outfit-Bold.ttf'),
    );
    this.faviconSvg = fs.readFileSync(
      path.join(assetsDir, 'favicon.svg'),
      'utf-8',
    );
  }

  private async solidBackground(size: number): Promise<Buffer> {
    return sharp({
      create: { width: size, height: size, channels: 4, background: '#1a1a1a' },
    })
      .png()
      .toBuffer();
  }

  private wrapText(text: string, fontSize: number, maxWidth: number): string[] {
    const words = text.split(' ');
    const lines: string[] = [];
    let current = '';
    for (const word of words) {
      const test = current ? current + ' ' + word : word;
      if (this.font.getAdvanceWidth(test, fontSize) > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
    return lines;
  }

  private textToPath(
    text: string,
    x: number,
    y: number,
    fontSize: number,
    fill: string,
  ): string {
    const p = this.font.getPath(text, x, y, fontSize);
    return `<path d="${p.toPathData()}" fill="${fill}"/>`;
  }

  async generateCoverImage(
    artistName: string,
    artistImageUrl?: string,
  ): Promise<string> {
    const size = 640;

    // 1. Process the Background Artist Image
    let artistImgBuffer: Buffer;

    if (artistImageUrl) {
      try {
        const response = await fetch(artistImageUrl);
        const arrayBuffer = await response.arrayBuffer();

        artistImgBuffer = await sharp(Buffer.from(arrayBuffer))
          .resize(size, size, { fit: 'cover' })
          .grayscale()
          .linear(1.2, -20)
          .ensureAlpha()
          .composite([
            {
              input: Buffer.from(
                `<svg><rect width="${size}" height="${size}" fill="black" fill-opacity="0.3"/></svg>`,
              ),
              top: 0,
              left: 0,
            },
          ])
          .toBuffer();
      } catch {
        artistImgBuffer = await this.solidBackground(size);
      }
    } else {
      artistImgBuffer = await this.solidBackground(size);
    }

    // 2. Build favicon for upper-left corner
    const iconSize = 64;
    const margin = 30;
    const faviconBuffer = await sharp(Buffer.from(this.faviconSvg))
      .resize(iconSize, iconSize)
      .png()
      .toBuffer();

    // 3. Build artist name overlay — split into lines that fit
    const displayName = artistName.toUpperCase();
    const maxWidth = size - margin * 2;
    const artistFontSize = displayName.length > 12 ? 80 : 110;
    const lines = this.wrapText(displayName, artistFontSize, maxWidth);

    // Subtitle line
    const subtitleFontSize = 16;
    const subtitle = 'Generated by Setlist2Playlist.app';

    // Position from the bottom: subtitle first, then lines above it
    const subtitleY = size - margin;
    const lineHeight = artistFontSize * 1.1;
    const artistBaseY =
      subtitleY - subtitleFontSize * 1.5 - (lines.length - 1) * lineHeight;

    const linePaths = lines
      .map((line, i) =>
        this.textToPath(
          line,
          margin,
          artistBaseY + i * lineHeight,
          artistFontSize,
          '#ffffff',
        ),
      )
      .join('\n');

    const subtitlePath = this.textToPath(
      subtitle,
      margin,
      subtitleY,
      subtitleFontSize,
      'rgba(255,255,255,0.6)',
    );

    const overlaySvg = `
      <svg width="${size}" height="${size}" xmlns="http://www.w3.org/2000/svg">
        ${linePaths}
        ${subtitlePath}
      </svg>
    `;

    // 4. Composite everything
    const finalImage = await sharp(artistImgBuffer)
      .composite([
        { input: Buffer.from(overlaySvg), top: 0, left: 0 },
        { input: faviconBuffer, top: margin, left: size - margin - iconSize },
      ])
      .jpeg({ quality: 90 })
      .toBuffer();

    return finalImage.toString('base64');
  }
}
